export declare const venueAppV: import("convex/values").VUnion<"alpaca-options" | "polymarket" | "mt5" | "binance-futures", [import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures", "required">, import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures", "required">, ...import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures", "required">[]], "required", never>;
export declare const appV: import("convex/values").VUnion<"alpaca-options" | "polymarket" | "mt5" | "binance-futures" | "backend", [import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures" | "backend", "required">, import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures" | "backend", "required">, ...import("convex/values").VLiteral<"alpaca-options" | "polymarket" | "mt5" | "binance-futures" | "backend", "required">[]], "required", never>;
export declare const orderStatusV: import("convex/values").VUnion<"pending" | "partially_filled" | "filled" | "rejected" | "cancelled" | "expired" | "timed_out", [import("convex/values").VLiteral<"pending" | "partially_filled" | "filled" | "rejected" | "cancelled" | "expired" | "timed_out", "required">, import("convex/values").VLiteral<"pending" | "partially_filled" | "filled" | "rejected" | "cancelled" | "expired" | "timed_out", "required">, ...import("convex/values").VLiteral<"pending" | "partially_filled" | "filled" | "rejected" | "cancelled" | "expired" | "timed_out", "required">[]], "required", never>;
export declare const orderActionV: import("convex/values").VUnion<"entry" | "adjustment" | "close" | "modify" | "cancel", [import("convex/values").VLiteral<"entry" | "adjustment" | "close" | "modify" | "cancel", "required">, import("convex/values").VLiteral<"entry" | "adjustment" | "close" | "modify" | "cancel", "required">, ...import("convex/values").VLiteral<"entry" | "adjustment" | "close" | "modify" | "cancel", "required">[]], "required", never>;
export declare const orderTransitionTypeV: import("convex/values").VUnion<"submission" | "status_change" | "modify_attempt" | "cancel_attempt" | "timeout_decision" | "terminal", [import("convex/values").VLiteral<"submission" | "status_change" | "modify_attempt" | "cancel_attempt" | "timeout_decision" | "terminal", "required">, import("convex/values").VLiteral<"submission" | "status_change" | "modify_attempt" | "cancel_attempt" | "timeout_decision" | "terminal", "required">, ...import("convex/values").VLiteral<"submission" | "status_change" | "modify_attempt" | "cancel_attempt" | "timeout_decision" | "terminal", "required">[]], "required", never>;
export declare const severityV: import("convex/values").VUnion<"critical" | "warning" | "info", [import("convex/values").VLiteral<"critical" | "warning" | "info", "required">, import("convex/values").VLiteral<"critical" | "warning" | "info", "required">, ...import("convex/values").VLiteral<"critical" | "warning" | "info", "required">[]], "required", never>;
export declare const eventTypeV: import("convex/values").VUnion<"filled" | "rejected" | "cancelled" | "submission" | "intent" | "validation" | "fill_update", [import("convex/values").VLiteral<"filled" | "rejected" | "cancelled" | "submission" | "intent" | "validation" | "fill_update", "required">, import("convex/values").VLiteral<"filled" | "rejected" | "cancelled" | "submission" | "intent" | "validation" | "fill_update", "required">, ...import("convex/values").VLiteral<"filled" | "rejected" | "cancelled" | "submission" | "intent" | "validation" | "fill_update", "required">[]], "required", never>;
export declare const claimSourceV: import("convex/values").VUnion<"position" | "order", [import("convex/values").VLiteral<"position", "required">, import("convex/values").VLiteral<"order", "required">], "required", never>;
export declare const portfolioProviderStatusV: import("convex/values").VUnion<"healthy" | "degraded" | "stale", [import("convex/values").VLiteral<"healthy" | "degraded" | "stale", "required">, import("convex/values").VLiteral<"healthy" | "degraded" | "stale", "required">, ...import("convex/values").VLiteral<"healthy" | "degraded" | "stale", "required">[]], "required", never>;
export declare const providerOwnershipStatusV: import("convex/values").VUnion<"owned" | "unowned" | "orphaned", [import("convex/values").VLiteral<"owned" | "unowned" | "orphaned", "required">, import("convex/values").VLiteral<"owned" | "unowned" | "orphaned", "required">, ...import("convex/values").VLiteral<"owned" | "unowned" | "orphaned", "required">[]], "required", never>;
//# sourceMappingURL=validators.d.ts.map