
FROM oven/bun:1 AS pruner
WORKDIR /app

COPY package.json bun.lock turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

RUN bunx turbo prune @valiq-trading/backend --docker

# =========================================================================== #
# =========================================================================== #

FROM oven/bun:1 AS builder
WORKDIR /app

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/tsconfig.json ./tsconfig.json
COPY --from=pruner /app/turbo.json ./turbo.json

RUN bun install
COPY --from=pruner /app/out/full/ .
RUN bun run build

# =========================================================================== #
# =========================================================================== #

FROM oven/bun:1 AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps/backend ./apps/backend

WORKDIR /app/apps/backend

ENV NODE_ENV=production
EXPOSE 3100
CMD ["bun", "run", "src/index.ts"]

# =========================================================================== #
