import type { ExecutionResult, OrderIntent } from "./types";
import { type OrderAction, type OrderPersistenceAdapter, type OrderSnapshot, type TrackedOrderHandle, type WaitForOrderUpdateOptions } from "./orders";
import type { VenueAdapter, TradeEventLogger, OrderLifecycleConfig, OrderStatusCallback } from "./execution";
import type { Logger } from "./logger";
export declare class OrderLifecycleManager {
    private venue;
    private logger;
    private pollInterval;
    private timeout;
    private orderPersistence?;
    private tradeEventLogger?;
    private runId;
    private strategyId;
    private venueName;
    private onSnapshotUpdate?;
    private trackedOrders;
    constructor(venue: VenueAdapter, logger: Logger, config?: OrderLifecycleConfig, orderPersistence?: OrderPersistenceAdapter, tradeEventLogger?: TradeEventLogger, runId?: string, strategyId?: string, venueName?: string, onSnapshotUpdate?: (previousSnapshot: OrderSnapshot, currentSnapshot: OrderSnapshot) => void);
    registerSubmittedOrder(intent: OrderIntent, result: ExecutionResult, action: OrderAction, metadata?: Record<string, unknown>): Promise<TrackedOrderHandle | undefined>;
    waitForUpdate(orderId: string, onUpdate: OrderStatusCallback, options?: WaitForOrderUpdateOptions): Promise<OrderSnapshot>;
    resumeActiveOrders(onUpdate: OrderStatusCallback): Promise<OrderSnapshot[]>;
    getTrackedSnapshot(orderId: string): OrderSnapshot | null;
    getTrackedOrders(): OrderSnapshot[];
    getOrderSnapshot(orderId: string): Promise<OrderSnapshot | null>;
    recordModifyAttempt(orderId: string, changes: Partial<OrderIntent>, reason?: string): Promise<void>;
    recordCancelAttempt(orderId: string, reason?: string): Promise<void>;
    captureVenueUpdate(orderId: string, result: ExecutionResult, transitionType: "status_change" | "modify_attempt" | "cancel_attempt", reason?: string): Promise<OrderSnapshot>;
    stopTracking(orderId: string): void;
    stopAll(): void;
    private schedulePoll;
    private pollOrder;
    private applyExecutionResult;
    private handleDecision;
    private persistSnapshot;
    private persistTransition;
    private resolvePendingWaiters;
    private requireTrackedOrder;
    private createAlert;
    private fetchOrderStatusOnTimeout;
}
//# sourceMappingURL=order-tracker.d.ts.map