import { VENUE_APPS } from "@valiq-trading/core"
import * as executionSchemas from "./tool-contract-execution-schemas"
import * as marketDataSchemas from "./tool-contract-market-data-schemas"
import {
    okxOrderJsonSchema,
    okxOrderParamsSchema,
} from "./tools/okx-order-helpers"
import {
    mt5OrderJsonSchema,
    mt5OrderParamsSchema,
} from "./tools/mt5-order-helpers"
import type { ToolContractDefinition } from "./tool-contract-types"

export const toolContractDefinitions = [
    {
        name: "get_positions",
        category: "account",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Get all current open positions. Returns instrument, side, quantity, entry price, current price, and unrealized P&L for each position.",
            parameters: executionSchemas.emptyParamsSchema,
            jsonSchema: { type: "object", properties: {} },
            outputDescription: "Returns the open positions array or an empty array when nothing is open.",
            errorSemantics: "Returns current broker or dry-run state. Transport or adapter failures throw.",
        },
    },
    {
        name: "get_account",
        category: "account",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Get the strategy-scoped account state including allocated balance, buying power budget, margin usage, and strategy P&L.",
            parameters: executionSchemas.emptyParamsSchema,
            jsonSchema: { type: "object", properties: {} },
            outputDescription: "Returns the current normalized strategy account snapshot.",
            errorSemantics: "Returns current broker or dry-run state. Transport or adapter failures throw.",
        },
    },
    {
        name: "get_order_status",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Check the current fill status of a tracked order. Returns the latest status, fill progress, and lifecycle snapshot.",
            parameters: executionSchemas.orderIdParamsSchema,
            jsonSchema: {
                type: "object",
                properties: {
                    orderId: { type: "string", description: "The order ID to check" },
                },
                required: ["orderId"],
            },
            outputDescription: "Returns the normalized execution status plus any tracked order snapshot.",
            errorSemantics: "Known order lookup failures return a structured error payload instead of throwing.",
        },
    },
    {
        name: "cancel_order",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Cancel a pending unfilled order. Provide the order ID.",
            parameters: executionSchemas.orderIdWithReasonParamsSchema,
            jsonSchema: {
                type: "object",
                properties: {
                    orderId: { type: "string", description: "The order ID to cancel" },
                    reason: { type: "string", description: "Why the order is being cancelled" },
                },
                required: ["orderId"],
            },
            outputDescription: "Returns the normalized cancellation result plus any tracked order snapshot.",
            errorSemantics: "Validation or broker rejections are returned in the execution payload.",
        },
    },
    {
        name: "wait_for_order_update",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Wait for the next order lifecycle update in the current run. Use this when an order is still pending or partially filled and you need the refreshed snapshot before deciding what to do next.",
            parameters: executionSchemas.waitForOrderUpdateParamsSchema,
            jsonSchema: {
                type: "object",
                properties: {
                    orderId: { type: "string", description: "The tracked order ID to wait on" },
                    timeoutMs: { type: "number", description: "Optional maximum wait for this tool call in milliseconds" },
                },
                required: ["orderId"],
            },
            outputDescription: "Returns the refreshed tracked order snapshot after the next lifecycle update or timeout boundary.",
            errorSemantics: "Wait failures throw. Timeout behavior is surfaced through the returned polling state.",
        },
    },
    {
        name: "propose_order",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        variants: {
            "alpaca-options": {
                description: "Propose a new Alpaca multi-leg credit entry. Use a positive net-credit `limitPrice`, `day` time in force, and either a 2-leg one-sided credit vertical (bull put or bear call) or a 4-leg iron condor with explicit open semantics. The system converts the price to Alpaca's signed `mleg` wire format.",
                parameters: executionSchemas.alpacaOrderParamsSchema,
                jsonSchema: executionSchemas.alpacaOrderJsonSchema,
                outputDescription: "Returns the normalized execution result, risk validation, and tracked order snapshot for the structure.",
                errorSemantics: "Broker or policy rejections are returned in the execution payload.",
            },
            polymarket: {
                description: "Propose a Polymarket order using a canonical token ID plus exact market identity from search_markets or direct lookup. Never submit a condition ID, event slug, or question as the tradable instrument.",
                parameters: executionSchemas.polymarketOrderParamsSchema,
                jsonSchema: executionSchemas.polymarketOrderJsonSchema,
                outputDescription: "Returns the normalized execution result, risk validation, and tracked order snapshot for the proposed order.",
                errorSemantics: "Broker or policy rejections are returned in the execution payload. Estimated execution pricing is injected from live venue data.",
            },
            mt5: {
                description: [
                    "Propose a new MT5 order.",
                    "You must provide stopLoss and either takeProfit or riskRewardRatio, not both.",
                    "Position size is calculated automatically so that hitting your stop-loss loses exactly maxRiskPercent of account balance.",
                    "Do not specify quantity or lot size because it is computed for you.",
                    "Returns the execution result including computed lot size, risk amount, and risk-reward ratio.",
                ].join(" "),
                parameters: mt5OrderParamsSchema,
                jsonSchema: mt5OrderJsonSchema,
                outputDescription: "Returns the normalized execution result plus computed sizing, risk, and price verification details.",
                errorSemantics: "Pre-validation failures return a structured rejected payload instead of throwing.",
            },
            "okx-swap": {
                description: [
                    "Propose a new OKX perpetual swap entry order for a canonical instrument such as BTC-USDT-SWAP or ETH-USDT-SWAP.",
                    "You must provide stopLoss and either takeProfit or riskRewardRatio.",
                    "Position size is calculated automatically from maxRiskPercent and stop distance.",
                    "Leverage defaults to policy maxLeverage and cannot exceed it.",
                    "Only market and limit entries are supported in this execution path.",
                    "For filled entries, protective stop-loss and take-profit orders are attached automatically.",
                ].join(" "),
                parameters: okxOrderParamsSchema,
                jsonSchema: okxOrderJsonSchema,
                outputDescription: "Returns the normalized execution result plus computed sizing, leverage, and protection-order details.",
                errorSemantics: "Pre-validation failures return a structured rejected payload instead of throwing.",
            },
        },
    },
    {
        name: "propose_adjustment",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        variants: {
            "alpaca-options": {
                description: "Propose adjusting an existing position by adding to or partially reducing it. Provide the instrument, direction, and quantity of the adjustment. Include a reason for the adjustment.",
                parameters: executionSchemas.genericAdjustmentParamsSchema,
                jsonSchema: executionSchemas.genericAdjustmentJsonSchema,
                outputDescription: "Returns the normalized adjustment execution result plus risk validation details.",
                errorSemantics: "Broker or policy rejections are returned in the execution payload.",
            },
            polymarket: {
                description: "Propose adjusting an existing position by adding to or partially reducing it. Provide the instrument, direction, and quantity of the adjustment. Include a reason for the adjustment.",
                parameters: executionSchemas.genericAdjustmentParamsSchema,
                jsonSchema: executionSchemas.genericAdjustmentJsonSchema,
                outputDescription: "Returns the normalized adjustment execution result plus risk validation details.",
                errorSemantics: "Broker or policy rejections are returned in the execution payload. Estimated execution pricing is injected from live venue data.",
            },
            mt5: {
                description: [
                    "Propose adjusting an existing MT5 position by adding to it.",
                    "You must provide stopLoss and either takeProfit or riskRewardRatio, not both.",
                    "Position size is calculated automatically so that hitting your stop-loss loses exactly maxRiskPercent of account balance.",
                    "Do not specify quantity or lot size because it is computed for you.",
                    "Include a reason for the adjustment.",
                ].join(" "),
                parameters: mt5OrderParamsSchema,
                jsonSchema: mt5OrderJsonSchema,
                outputDescription: "Returns the normalized adjustment execution result plus computed sizing and risk details.",
                errorSemantics: "Pre-validation failures return a structured rejected payload instead of throwing.",
            },
            "okx-swap": {
                description: "Update protective stop-loss and take-profit orders for an existing OKX perpetual swap position.",
                parameters: executionSchemas.okxAdjustmentParamsSchema,
                jsonSchema: executionSchemas.okxAdjustmentJsonSchema,
                outputDescription: "Returns the protection-order update result including cancelled and recreated protection order IDs.",
                errorSemantics: "Missing protection levels or missing positions return a structured rejected payload instead of throwing.",
            },
        },
    },
    {
        name: "propose_close",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: VENUE_APPS,
        defaultVariant: {
            description: "Propose closing an entire position for a given instrument. Provide the instrument and a reason for closing.",
            parameters: executionSchemas.closeParamsSchema,
            jsonSchema: executionSchemas.closeJsonSchema,
            outputDescription: "Returns the normalized close execution result plus risk validation details.",
            errorSemantics: "Broker or policy rejections are returned in the execution payload.",
        },
    },
    {
        name: "modify_order",
        category: "execution",
        boundary: "shared",
        owner: "shared",
        compatibleVenues: ["alpaca-options", "polymarket", "mt5"],
        variants: {
            "alpaca-options": {
                description: "Modify a working Alpaca multi-leg options order. Supported changes are the positive net limit price and, if truly necessary, the structure quantity. The system handles Alpaca's signed `mleg` wire price.",
                parameters: executionSchemas.alpacaModifyOrderParamsSchema,
                jsonSchema: executionSchemas.alpacaModifyOrderJsonSchema,
                outputDescription: "Returns the normalized order modification result plus the refreshed tracked order snapshot.",
                errorSemantics: "Broker rejections are returned in the execution payload.",
            },
            polymarket: {
                description: "Modify a pending order. You can change the limit price, stop price, or quantity. At least one modification field must be provided.",
                parameters: executionSchemas.defaultModifyOrderParamsSchema,
                jsonSchema: executionSchemas.defaultModifyOrderJsonSchema,
                outputDescription: "Returns the normalized order modification result plus the refreshed tracked order snapshot.",
                errorSemantics: "Broker rejections are returned in the execution payload.",
            },
            mt5: {
                description: "Adjust stop-loss and or take-profit on an existing MT5 position using its numeric order ticket. Quantity and entry price changes are not supported.",
                parameters: executionSchemas.mt5ModifyOrderParamsSchema,
                jsonSchema: executionSchemas.mt5ModifyOrderJsonSchema,
                outputDescription: "Returns the normalized order modification result plus the refreshed tracked order snapshot.",
                errorSemantics: "Missing protective fields fail schema validation before execution. Broker rejections are returned in the execution payload.",
            },
        },
    },
    {
        name: "get_options_chain",
        category: "market-data",
        boundary: "venue-owned",
        owner: "alpaca-options",
        compatibleVenues: ["alpaca-options"],
        defaultVariant: {
            description: "Fetch the live Alpaca options chain for an underlying. Returns contracts with current bid and ask, midpoint, latest trade, greeks, implied volatility, open interest, and canonical executionCost derived from Alpaca market data.",
            parameters: marketDataSchemas.getOptionsChainParamsSchema,
            jsonSchema: marketDataSchemas.getOptionsChainJsonSchema,
            outputDescription: "Returns normalized options contracts with canonical executionCost fields and any pagination token from Alpaca.",
            errorSemantics: "Venue lookup failures throw.",
        },
    },
    {
        name: "get_quote",
        category: "market-data",
        boundary: "venue-owned",
        owner: "alpaca-options",
        compatibleVenues: ["alpaca-options"],
        defaultVariant: {
            description: "Fetch the latest live Alpaca quote for an equity underlying. Returns current bid, ask, last trade price, recent bars, and canonical executionCost.",
            parameters: marketDataSchemas.singleSymbolParamsSchema,
            jsonSchema: marketDataSchemas.getQuoteJsonSchema,
            outputDescription: "Returns the current normalized equity quote, recent bar snapshot, and canonical executionCost.",
            errorSemantics: "Venue lookup failures throw.",
        },
    },
    {
        name: "get_symbol_info",
        category: "market-data",
        boundary: "venue-owned",
        owner: "mt5",
        compatibleVenues: ["mt5"],
        defaultVariant: {
            description: "Fetch live MT5 symbol information including bid, ask, normalized spread with its unit, canonical executionCost, tick value, contract size, and volume constraints.",
            parameters: marketDataSchemas.singleSymbolParamsSchema,
            jsonSchema: marketDataSchemas.getSymbolInfoJsonSchema,
            outputDescription: "Returns normalized MT5 symbol metadata, including spread, spreadUnit, and canonical executionCost, or a found:false payload when the symbol is unavailable.",
            errorSemantics: "Missing symbols return found:false. Worker or transport failures throw.",
        },
    },
    {
        name: "get_market_price",
        category: "market-data",
        boundary: "venue-owned",
        owner: "venue-extension",
        compatibleVenues: ["polymarket", "okx-swap"],
        variants: {
            polymarket: {
                description: "Fetch the current Polymarket midpoint, best bid, best ask, spread, optional executable price, liquidityWarning, and canonical executionCost derived from one /book snapshot.",
                parameters: marketDataSchemas.polymarketMarketPriceParamsSchema,
                jsonSchema: marketDataSchemas.polymarketMarketPriceJsonSchema,
                outputDescription: "Returns normalized Polymarket pricing, spread, liquidity warning, and canonical executionCost information for the requested token.",
                errorSemantics: "Venue lookup failures throw.",
            },
            "okx-swap": {
                description: "Fetch the current OKX swap mark price, last price, best bid, best ask, spread, funding rate, next funding time, and canonical executionCost for an instrument.",
                parameters: marketDataSchemas.singleSymbolParamsSchema,
                jsonSchema: marketDataSchemas.okxMarketPriceJsonSchema,
                outputDescription: "Returns normalized OKX swap pricing, spread, funding, and canonical executionCost information for the requested instrument.",
                errorSemantics: "Venue lookup failures throw.",
            },
        },
    },
    {
        name: "get_order_book",
        category: "market-data",
        boundary: "venue-owned",
        owner: "venue-extension",
        compatibleVenues: ["polymarket", "okx-swap"],
        variants: {
            polymarket: {
                description: "Fetch the live Polymarket order book for a token. Use this to assess spread and available depth before sizing an order.",
                parameters: marketDataSchemas.polymarketOrderBookParamsSchema,
                jsonSchema: marketDataSchemas.polymarketOrderBookJsonSchema,
                outputDescription: "Returns normalized Polymarket order book depth for the requested token.",
                errorSemantics: "Venue lookup failures throw.",
            },
            "okx-swap": {
                description: "Fetch the live OKX swap order book for an instrument. Use this to assess depth and likely slippage before sizing larger entries.",
                parameters: marketDataSchemas.okxOrderBookParamsSchema,
                jsonSchema: marketDataSchemas.okxOrderBookJsonSchema,
                outputDescription: "Returns normalized OKX swap order book depth for the requested instrument.",
                errorSemantics: "Venue lookup failures throw.",
            },
        },
    },
    {
        name: "search_markets",
        category: "market-data",
        boundary: "venue-owned",
        owner: "polymarket",
        compatibleVenues: ["polymarket"],
        defaultVariant: {
            description: "Discover active Polymarket markets via Gamma, or look up a direct condition ID or market slug. Use this to get a top-liquid candidate list and token IDs first, then request live prices or order books only for your best candidate markets.",
            parameters: marketDataSchemas.searchMarketsParamsSchema,
            jsonSchema: marketDataSchemas.searchMarketsJsonSchema,
            outputDescription: "Returns normalized Polymarket market discovery results. By default this is Gamma-only metadata plus token IDs; optional live price enrichment adds venue pricing and executionCost for a tightly capped token subset.",
            errorSemantics: "Empty requests throw before venue lookup. Harmless optional enrichment fields are ignored when enrichment is disabled.",
        },
    },
    {
        name: "web_search",
        category: "web",
        boundary: "venue-owned",
        owner: "polymarket",
        compatibleVenues: ["polymarket"],
        defaultVariant: {
            description: "Search the internet for information. Returns a list of results with title, URL, and snippet. Useful for market news, event research, and finding current information.",
            parameters: marketDataSchemas.webSearchParamsSchema,
            jsonSchema: marketDataSchemas.webSearchJsonSchema,
            outputDescription: "Returns normalized web search results.",
            errorSemantics: "Provider failures throw unless the provider itself returns a degraded result.",
        },
    },
    {
        name: "web_fetch",
        category: "web",
        boundary: "venue-owned",
        owner: "polymarket",
        compatibleVenues: ["polymarket"],
        defaultVariant: {
            description: "Fetch the content of a specific URL and return it as text. HTML tags are stripped. Content is truncated to maxLength characters.",
            parameters: marketDataSchemas.webFetchParamsSchema,
            jsonSchema: marketDataSchemas.webFetchJsonSchema,
            outputDescription: "Returns fetched content, truncated content length, or a structured fetch error payload.",
            errorSemantics: "HTTP and fetch failures are returned as payload errors instead of throwing where possible.",
        },
    },
] satisfies readonly ToolContractDefinition[]
